In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("harishyadav0506/youtube-shorts-dataset")

print("Path to dataset files:", path)

c:\Users\joshu\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\joshu\.cache\kagglehub\datasets\harishyadav0506\youtube-shorts-dataset\1.archive...

100%|██████████| 16.7k/16.7k [00:00<00:00, 15.6MB/s]

Extracting files...
Path to dataset files: C:\Users\joshu\.cache\kagglehub\datasets\harishyadav0506\youtube-shorts-dataset\versions\1

In [2]:
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("harishyadav0506/youtube-shorts-dataset")

print("Path to dataset files:", path)

print(os.listdir(path))
file_path = os.path.join(path, "youtube_shorts_dataset.csv")
df = pd.read_csv(file_path)
df

Path to dataset files: C:\Users\joshu\.cache\kagglehub\datasets\harishyadav0506\youtube-shorts-dataset\versions\1
['youtube_shorts_dataset.csv']

,type,video.thumbnails,video.title,video.videoId
0,video,[],Jacob Fatu did as he was told,hs-KQfkDEpw
1,video,[],You can run but you can't hide from La Primera 😈,qxSQULBypcQ
2,video,[],Ngl that was an impressive imitation 😂,cmpS0G6Jrmo
3,video,[],BFT to the OTC… YEAH!,n9MsZe17xT8
4,video,[],You love to see it! 🤝,s_eXB1mzNHQ
...,...,...,...,...
475,video,[],CM Punk and Cody Rhodes made it work tonight. ...,sZwpQsRtONY
476,video,[],Nick Aldis what are you doing???? 🫢 #SNME,P2mklShoVcY
477,video,[],EVERYBODY’S DOWN!! This match is absolutely in...,_ZQmNQ3IWZ4
478,video,[],Gunther just gouged CM Punk’s eye! Whatever it...,IMqMV55xoqM
479,video,[],Can they coexist though?? 👀 #SNME,rKc_2iaSMlo

In [1]:
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("harishyadav0506/youtube-shorts-dataset")

print("Path to dataset files:", path)

print(os.listdir(path))
file_path = os.path.join(path, "youtube_shorts_dataset.csv")
df = pd.read_csv(file_path)

df = df.drop_duplicates()
df = df.dropna()

df

c:\Users\joshu\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\joshu\.cache\kagglehub\datasets\harishyadav0506\youtube-shorts-dataset\versions\1
['youtube_shorts_dataset.csv']

,type,video.thumbnails,video.title,video.videoId
0,video,[],Jacob Fatu did as he was told,hs-KQfkDEpw
1,video,[],You can run but you can't hide from La Primera 😈,qxSQULBypcQ
2,video,[],Ngl that was an impressive imitation 😂,cmpS0G6Jrmo
3,video,[],BFT to the OTC… YEAH!,n9MsZe17xT8
4,video,[],You love to see it! 🤝,s_eXB1mzNHQ
...,...,...,...,...
475,video,[],CM Punk and Cody Rhodes made it work tonight. ...,sZwpQsRtONY
476,video,[],Nick Aldis what are you doing???? 🫢 #SNME,P2mklShoVcY
477,video,[],EVERYBODY’S DOWN!! This match is absolutely in...,_ZQmNQ3IWZ4
478,video,[],Gunther just gouged CM Punk’s eye! Whatever it...,IMqMV55xoqM
479,video,[],Can they coexist though?? 👀 #SNME,rKc_2iaSMlo